<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-A9IKKQ4" failures="1" tests="14" name="PetTests" time="22.019" errors="0" timestamp="2025-08-13T21:56:47 IST">
  <testcase classname="api.test.UserTests" name="testPostUser" time="2.92"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="1.186">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testGetUserByName(UserTests.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.UserTests" name="testUpdateUserByName" time="2.358"/>
  <testcase classname="api.test.UserTests" name="testDeleteByUserName" time="1.187"/>
  <testcase classname="api.test.UserTests2" name="testPostUser" time="1.181"/>
  <testcase classname="api.test.UserTests2" name="testGetUserByName" time="1.166"/>
  <testcase classname="api.test.UserTests2" name="testUpdateUserByName" time="2.35"/>
  <testcase classname="api.test.UserTests2" name="testDeleteByUserName" time="1.172"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="1.199"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="1.201"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="1.184"/>
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.169"/>
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.171"/>
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.159"/>
</testsuite> <!-- PetTests -->
